### ISSUE TITLE
error after installation on Ubuntu 22.04

### ISSUE THREAD

**Issue by maxmonz69** [osmank3/otp-keys#14]
This is the error

TypeError: otp is null

Stack trace:
  Otp@/home/massimo/.local/share/gnome-shell/extensions/otp-keys@osmank3.net/prefs.js:83:9
  _sync@/home/massimo/.local/share/gnome-shell/extensions/otp-keys@osmank3.net/prefs.js:223:39
  OtpList@/home/massimo/.local/share/gnome-shell/extensions/otp-keys@osmank3.net/prefs.js:107:14
  OtpKeysSecretListWidget@/home/massimo/.local/share/gnome-shell/extensions/otp-keys@osmank3.net/prefs.js:285:24
  OtpKeysSettingsPageWidget@/home/massimo/.local/share/gnome-shell/extensions/otp-keys@osmank3.net/prefs.js:252:29
  buildPrefsWidget@/home/massimo/.local/share/gnome-shell/extensions/otp-keys@osmank3.net/prefs.js:842:12
  _init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:32:44
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:129:33
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

**Comment by osmank3** [comment]
I have successfully replicated the error and will implement the necessary corrections in the subsequent release.

**Comment by osmank3** [comment]
With 6e0391859699974f30241cdc3f84427c36fb8eac commit, error fixed and send to review, after that you can update from extensions.gnome.org.
