### ISSUE TITLE
Copy to clipboard by selecting the item

### ISSUE THREAD

**Issue by dlastov** [osmank3/otp-keys#6]
At this moment I need to click on the small icon next to the label and code.
Would it be possible to remove the icon and simply copy the code by clicking anywhere on the line?
Also, it seems not necessary to display the code, just clickable label that copies the code to the clipboard would be sufficient.

**Comment by osmank3** [comment]
Thank you for your advice.
On next version I will remove the copy button and copying to clipboard will work clicking on the line.
But displaying code is necessary for usability on other devices.

**Comment by dlastov** [comment]
Amazing, I see it is already done and works perfectly. Thank you!
