### ISSUE TITLE
FR: add the possibility to disable notifications

### ISSUE THREAD

**Issue by ogarcia** [osmank3/otp-keys#8]
With the latest version when you click on an element it copies it to the clipboard and brings up the notification with the text _Code copied to clipboard._, as clicking on an element already closes the menu this feedback by notification is not necessary (at least for me). As I understand that there will be users who find the notification interesting, it would be appropriate that in the settings there is an option to enable or disable it. What do you think?

**Comment by osmank3** [comment]
Thanks for your advice. Why not? :smile: I will add that feature for you.

**Comment by osmank3** [comment]
Feature added and send to review, after that you can update from extensions.gnome.org.
